### PR TITLE
Submission of assignment-1 - Python

### PR DESCRIPTION
**Pull request by Jasonpereira0**
TITLE: UofT-DSI | Data Science - Python Assignment 1 - Jason Pereira

## What changes are you trying to make? (e.g. Adding or removing code, refactoring existing code, adding reports)
Building an Anagram checker for two strings that does the following:

Part 1
- Compares the length of the two strings.
- Checks and compares both strings for duplicate characters in lower case.
- Checks and compares all characters of both strings in lower case.
- Returns True if all of the above are met and False if not.

Part 1 - Alternative method
- Compares the length of the two strings.
- Sorts both strings and compares all characters of both strings in lower case.
- Returns True if all of the above are met and False if not.

Part 2
- Compares the length of the two strings.
- If the case sensitive Boolean is False, checks and compares all characters of both strings regardless of case sensitivity.
- If the case sensitive Boolean is True, sorts both strings and compares all characters of both strings in a case-sensitive manner.
- Returns True if all the above are met and False if not.

Part 2 - Alternative method
 - Compares the length of the two strings.
- Negates the case sensitive Boolean to False, checks and compares all characters of both strings regardless of case sensitivity.
- If the case sensitive Boolean is True, sorts both strings and compares all characters of both strings in a case-sensitive manner.
- Returns True if all the above are met and False if not.

## What did you learn from the changes you have made?

I learned how to use if, and, or, elif, while, for, not, sorted, equal to, not equal to, etc., functions and operators. Also learned how to define a function and call it. Learned how to return and print an output. 

## Was there another approach you were thinking about making? If so, what approach(es) were you thinking of?

Yes I have used my basic knowledge of code framework in C and C++ over 18 years ago to attempt an approach which is exhaustive but also used the learnings from the sessions to create a more optimized code using sorted and .lower() and .upper(). I have included the alternative methods for both parts in this assignment to showcase my approaches. 

## Were there any challenges? If so, what issue(s) did you face? How did you overcome it?

Yes, it took a long time to construct the initial approach and let the content sink in develop the alternative optimized version.

## How were these changes tested?

I tested all the code and included as many edge cases I could think of to cover all grounds such as string length, duplicate characters, upper case and lower characters util the output was consistent with the expectations.

## A reference to a related issue in your repository (if applicable)

N/A

## Checklist
- [ X] I can confirm that my changes are working as intended

### CODE REVIEW

**Comment by pedram-aliniaye-asli** [comment]
You did a great job here!

A few things to notice:
Part 1:
Your function provides a robust approach to checking for anagrams, but there are a few redundant steps and issues with logic flow.
1 -You already ensure both strings have the same character counts using char_count_a and char_count_b. If these dictionaries are equal, the words are anagrams. The additional while loop is unnecessary.
2 -You lowercased both strings before creating the dictionaries. This handles case-insensitivity already, so there's no need to check for uppercase versions explicitly.
3- Comparing dictionaries is enough to verify anagrams. Sorting or iterating further isn't needed.

Part2 :
Your current implementation in this step is incomplete and has a few logical flaws. 
    The while loop: It doesn't seem necessary to check if two words are anagrams. Instead, comparing sorted versions of the strings or using a dictionary to count characters would be more efficient.
    Case sensitivity handling: When is_case_sensitive is True, you should directly compare the words with their respective cases. When is_case_sensitive is False, you should compare the lowercased versions of the words.
    Return values in the while loop: The return statement inside the while loop is wrong because the function will return immediately without checking all characters.
    
Please go ahead and do the modifications and then let me know, Thanks!

**Comment by Jasonpereira0** [comment]
Hi Pedram,

Thanks you for the valuable feedback and guidance. A good example of me overthinking to solve a seemingly simple problem :)

I have incorporated the changes and pushed the modified code removing the redundancies and also adding the missing logic in part 2,

I've done sanity checks and also ran all the possible outcomes in the test examples to ensure the  desired outcome and explained the reasoning behind it, however please let me know if I missed anything.

Thanks!

Jason

**Comment by pedram-aliniaye-asli** [comment]
you did a great job here!
It's perfect!
Please go ahead and close this pull request now. Thanks!

**Comment by Jasonpereira0** [comment]
Thank you!

**Pull request closed without merging**
